### ISSUE TITLE
Linking schemas from other dialects

### ISSUE THREAD

**Issue by antoniogarrote** [aml-org/aml2html#14] opened 2019-09-22 22:24 UTC
Right now links to schemas linked from other dialect files is broken.

Either the link is generated just as a label with `file_alias.ExternalSchema` or a link to the current dialect instead of the external one are generated.

Links should be generated only with the name of the schema and correct link to the right HTML file.

**Comment by postatum** [comment] 2019-09-26 09:40
@antoniogarrote I managed to get `a link to the current dialect instead of the external one are generated.`, but how do I get a `just as a label with file_alias.ExternalSchema` ?

**Comment by postatum** [comment] 2019-10-01 07:27
@antoniogarrote I've merged a fix for 

> a link to the current dialect instead of the external one are generated.

But I couldn't reproduce 

> link is generated just as a label with `file_alias.ExternalSchema`

The fixed I merged may fix both though.

When you have time, please test and close this issue if both are fixed.

**Comment by postatum** [comment] 2019-10-21 06:49
Closing because no answer.

**Closed as completed by postatum** 2019-10-21 06:49 UTC
Labels: bug
